COPY INTO CORTEX_ANALYST_HEALTHCARE.SALES_DATA.HCP_ANALYTICS_SUMMARY
FROM @raw_data
FILES = ('hcp_analytics_summary.csv')
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_DELIMITER = ',',
    TRIM_SPACE = FALSE,
    FIELD_OPTIONALLY_ENCLOSED_BY = NONE,
    REPLACE_INVALID_CHARACTERS = TRUE,
    DATE_FORMAT = AUTO,
    TIME_FORMAT = AUTO,
    TIMESTAMP_FORMAT = AUTO,
    EMPTY_FIELD_AS_NULL = FALSE,
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
ON_ERROR = CONTINUE
FORCE = TRUE;

COPY INTO CORTEX_ANALYST_HEALTHCARE.SALES_DATA.REP_PRODUCT_PERFORMANCE
FROM @raw_data
FILES = ('rep_product_performance.csv')
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_DELIMITER = ',',
    TRIM_SPACE = FALSE,
    FIELD_OPTIONALLY_ENCLOSED_BY = NONE,
    REPLACE_INVALID_CHARACTERS = TRUE,
    DATE_FORMAT = AUTO,
    TIME_FORMAT = AUTO,
    TIMESTAMP_FORMAT = AUTO,
    EMPTY_FIELD_AS_NULL = FALSE,
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
ON_ERROR = CONTINUE
FORCE = TRUE;


COPY INTO CORTEX_ANALYST_HEALTHCARE.SALES_DATA.ELITE_CLUB_SCORES
FROM @raw_data
FILES = ('elite_club_scores.csv')
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_DELIMITER = ',',
    TRIM_SPACE = FALSE,
    FIELD_OPTIONALLY_ENCLOSED_BY = NONE,
    REPLACE_INVALID_CHARACTERS = TRUE,
    DATE_FORMAT = AUTO,
    TIME_FORMAT = AUTO,
    TIMESTAMP_FORMAT = AUTO,
    EMPTY_FIELD_AS_NULL = FALSE,
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
ON_ERROR = CONTINUE
FORCE = TRUE;


