USE DATABASE PHARMA_ANALYST;
USE SCHEMA PRESCRIPTION_TIMESERIES;

COPY INTO PHARMA_ANALYST.PRESCRIPTION_TIMESERIES.PRESCRIPTION
FROM @raw_data
FILES = ('prescription.csv')
FILE_FORMAT = (
    TYPE = CSV,
    SKIP_HEADER = 1,
    FIELD_DELIMITER = ',',
    TRIM_SPACE = TRUE,
    FIELD_OPTIONALLY_ENCLOSED_BY = '"',
    REPLACE_INVALID_CHARACTERS = TRUE,
    DATE_FORMAT = AUTO,
    TIME_FORMAT = AUTO,
    TIMESTAMP_FORMAT = AUTO,
    EMPTY_FIELD_AS_NULL = FALSE,
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
ON_ERROR = CONTINUE
FORCE = TRUE;


